language: julia
os:
  - linux
  - windows
  - osx

julia:
  - 1
  # - nightly

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
